### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by NicoHdM** [NicoHenzel/Project_AppliedStatistics_BA_NH#1]
### Peer review team

- Peer review by: Group D
- Names of team members that participated in this review: Nico Gerspach, Jonas Lüttmann
### Goal of the project

Gruppe C möchte untersuchen, ob es eine Korrelation zwischen der Höhe des Haushaltseinkommens und der Todesrate in den USA gibt. Hierzu verwenden sie Daten, die bereits unabhängig voneinander untersucht wurden, um diese anschliessend über einen join zu verknüpfen. 

### Data

- Describe the data used or collected, if any. Is the data adequate for the project?

   Verwendet werden 2 Datenquellen. Eine Datei enthält die Median Haushaltseinkommen für die Jahre 1990, 2000, 2005, 2010 and    2013-2017. Die andere Datei enthält die Sterbefälle pro Staat und nach Todesursache differenziert.

   Ja, die Daten sind relevant für die Untersuchung der Frage.

### Approach, tools and methods

- Describe the approaches, tools, and methods that will be used.

1. Approach:
Es wurde ein klassischer Ansatz gewählt indem zuerst die Daten import anschliessend ein Überblick über die Daten verschafft wurden. Danach wurden die Daten korrigiert und eine Variablenliste erstellt. Danach wurden die Daten in Trainings- und Testdaten für die Modellierung gesplittet. Um Zusammenhänge in den Daten zu erkennen, wurden Ansätze aus der deskiptiven und explorativen Statistik angewendet und ein Blick auf die Beziehungen innerhalb der Daten geworfen. Daraufhin begann die Modellierung. Es wurden Modelle ausgewählt, trainiert und angepasst, um im letzten Schritt auf Basis der Testdaten evaluiert zu werden.
   

2. Tools:  
Als Tools wurden bekannte Bibliotheken wie Numpy und Pandas benutzt. Für die Ergänzung der fehlenden Werte wurde die Bibliotheken missingno verwendet. Zur Visualisierung wurde Altair in Kombination mit Matplotlib und Seaborn genutzt. 
Für die Berechnung der Statistiken wurden Scikit-learn verwendet. 

3. Methods:  
Zuerst wurden Daten korrigiert. Irrelevante Spalten wurden entfernt, Spaltennamen wurde geändert, Datensätze wurden mittels Join-Funktion verbunden, fehlende Werte für die Median Haushaltseinkommen wurden durch eine Berechnung ergänzt (KNN-Imputation). Anschliessend wurden die Daten in Trainings- und Testdaten getrennt.  
Um einen besseren Überblick über die Daten zu erhalten, wurden mittels deskriptiver Statistiken wichtige statistische Werte emittelt.
Danach wurden mittels explorativer Datenanalyse folgende Diagramme erstellt: 
- Unterschiedliche Diagramme zur Darstellung der Verteilung. Hauptsächlich Histogramme (als Linie oder als Säulendiagramm) 
- Diverse Streudiagramm 

   Um die Beziehungen der verschiedenen Variablen zu untersuchen, wurde die Korrelation in einer Matrix dargestellt.
Lineare- und Lasso Regression wurden genutzt, um ein Model zu erstellen.   
Um die Regressionsmethoden zu trainieren und zu validieren, wurde je Methode eine Cross-Validation mit 5 Folds durchgeführt. Nach der Anpassung der Modelle mit den Trainingsdaten, wurden jeweils die Koeffizienten berechnet. Anschliessend wurden anhand der Testdaten wichtige statistische Werte zur Beurteilung des Modells berechnet (z.B. R^2).  

### Lack of clarity

- Is there anything that is unclear from the proposal? 

1. aktuell in [21]: df_explore = df_train
"First we copy the training dataframe into another variable. This way we prevent the training data to be accidentally changed during data exploration:"
Müsste für eine Kopie des DF nicht die Funktion df.copy verwendet werden? Unserer Meinung nach wird df_train verändert, sobald eine Anpassung in df_explore vorgenommen wird. 

2. "age adjusted death rate:" 
- Hier ist uns noch unklar bzw. wir können nirgends genau lesen, was das bedeutet.
- Ist das ein absoluter Wert oder ist das eine Rate in %?
- Was sagt eine Rate von 1061.2 (max. age_adjusted_death_rate)? 

3. Zeitverlauf 
Zuerst schreibt ihr bei "Relationships" diesen Kommentar, was so viel bedeutet, dass der Zeitverlauf vermutlich relevant ist für die Korrelation: "The correlation matrix shows, that there is a moderate to strong negative correlation for year and median_household_income. That means, that our hyphothesis is supported by the data. The data shows in addition, that the more years pass, the less people die (looking at data from 1999-2017) which could be explained by the improvements in the medical sector as well as the standard of living. To verifiy this assumption we would need more data."
Anschliessend bei "Model type" schreibt ihr dann, dass die Jahre herausgenommen werden, da keine Zeitreihenanalyse erstellt wird.    
"We will also drop the year column since we are not evaluation a time series and only use the extra data provided:"
Habt ihr das rausgenommen, da die Korrelation bei nur - 0.078... liegt und somit kaum relevant ist für die weiteren Untersuchungen?

### Possible improvements

- Provide constructive feedback on how the team might be able to improve their project.Make sure your feedback includes at least one comment on the modeling aspect of the project, but do feel free to comment on aspects beyond the modeling.

1. Aus unserer Sicht würde es sinvoll sein, die Daten für die Regressionsmodelle nur für jeweils einzelne Jahre zu betrachten damit die Zeitspanne (von 18 Jahren) nicht das Ergebnis beeinflusst.   

2. Ergänzt werden können die Modelle um die Multiple Regression. Hierbei kann die Todesursache als kategoriale Variable miteinbezogen werden, um zu prüfen, ob damit die unterschiedlichen Zusammehänge besser dargestellt werden können (ähnlich Scatterplot Grafik). Hierdurch würde die Forschungsfrage um den Aspekt der exakten Todesursache in Abhängikeit vom Median Haushaltseinkommen erweitert werden.   

3. Spannend wäre, wenn Ihr nur die Zeilen der Staaten nutzen, würdet die auch ein Median Haushaltseinkommen haben, sodass nur 42% des Datensatzes genutzt werden.  

### Presentation

- What aspect of this project are you most interested in and would like to see highlighted in the final presentation?

1. Interessant bei der finalen Präsentation wäre zu wissen, wie der angereicherte Datensatz (Imputation) im Vergleich mit dem reduzierten Datensatz verhält und wie sich das auf das Ergebnis auswirkt.

2. Es wäre zudem interessant, wenn ihr für die Präsentation ein weiteres von euch bereits genanntes Modell erstellt, um zu schauen, ob es dadurch zu einer Verbesserung kommt.    

### Organization

- Provide constructive feedback on any issues with file and/or code organization.

1. Um besser nachvollziehen zu können was bei welchen Commits getan wurde wäre eine ausführlichere Beschreibung hilfreich. 

2. Die Grafiken können in Github teilweise nicht angezeigt werden (liegt aber an Github selbst). 

### Further comments

- Any further comments or feedback?

   Prinzipiell wurde die Draft-Analysis aber sehr gut beschrieben und die einzelnen Codes sehr gut erklärt.

**Comment by NicoHenzel** [comment]
- Erklärung für Age Adjusted Death rate angepasst
- Argumentation für Year column ergänzt
- Multiple Regression macht Sinn als Ausblick, nicht im Rahmen des Projektumfangs
- Vergleich zu Model mit und ohne Imputation wird noch angefertigt
- Weitere Modelle werden ggfs. (abhängig von der verfügbaren Zeit) im Appendix eingefügt
- Ausblick anpassen um Zusammenhang Regierung und Median Income (auch unterjährig)
